### ISSUE TITLE
Language tag after store.find function

### ISSUE THREAD

**Issue by StanCallewaert** [RubenVerborgh/N3.js#50] opened 2015-07-27 12:57 UTC
Hi Ruben

## Problem

I'm working on a DCAT validator for oSoc15 and I seem to have a problem with the language tag after finding a triple his object in the store.

The problem is that if i try to find a certain triple with the find function and I console.log the triple his object i get:
De DataTank Demo"^^http://www.w3.org/1999/02/22-rdf-syntax-ns#langString

While the triple i inserted was: 
<http://demo.thedatatank.com/api/dcat> dc:title "De DataTank Demo"@nl ;

There is an "nl" tag behind the object of the triple when i insert it in the store but I can't get it when I use the find function.

## How I've tried to solve the problem

I've looked through your documentation and saw that there is a function:
N3Util.getLiteralLanguage('"Mickey Mouse"@en');

But the triple object I get back from the find function doesn't return the literal with the language tag so concrete the find function would return: "Mickey Mouse" without @en.

Is there a way to solve this issue, if there is i'll be happy to hear it. Thanks in advance!!

Btw: you can find my DCAT validator project here: https://github.com/oSoc15/dcat-validator.js

**Comment by RubenVerborgh** [comment] 2015-07-27 12:58
Thanks @StanCallewaert, seems like a bug, will investigate.

**Comment by RubenVerborgh** [comment] 2015-07-27 16:24
I cannot reproduce this behavior with the following code:

```JavaScript
var store = new N3.Store();
store.addTriple('http://demo.thedatatank.com/api/dcat',
                'http://purl.org/dc/elements/1.1/title',
                '"De DataTank Demo"@nl');
var triple = store.find()[0];
console.log(triple.object);
console.log(N3.Util.getLiteralLanguage(triple.object));
```

Please provide a minimal failing example.

**Comment by RubenVerborgh** [comment] 2015-08-21 14:51
Since this bug went unconfirmed, I'm closing it for now. Feel free to reopen if you can confirm.

**Closed by RubenVerborgh** 2015-08-21 14:51 UTC
Labels: bug, unconfirmed
